Repository izumizawa/mc426y2023, pull requests merged in 2023-06, with the labels that each got.

#68 Testes e Liberação de Software: Técnicas de Teste de Software
  package.json
  src/RestaurantSignUpCEP.spec.js
  src/RestaurantSignUpCEP.spec.js.snap
  src/RestaurantSignUpCNPJ.spec.js
  src/RestaurantSignUpEmail.spec.js
  src/RestaurantSignUpSenha.spec.js
  src/__snapshots__/RestaurantSignUpCNPJ.spec.js.snap
  src/__snapshots__/RestaurantSignUpEmail.spec.js.snap
  src/__snapshots__/RestaurantSignUpSenha.spec.js.snap
Labels: Avaliacao A5

#71 Readme update av4 1
  src/main/js/assets/images/diagramaN3.jpeg
Labels: Avaliação A4.1

#73 Feature/logistica de pedidos
  src/main/js/App.js
  src/main/js/components/AppBar.js
  src/main/js/components/OrderCard.js
  src/main/js/components/OrderInfo.js
  src/main/js/components/OrderItem.js
  src/main/js/components/OrderStatusDropdown.js
  src/main/js/hooks/OrderUpdateStorage.js
  src/main/js/pages/Login.js
  src/main/js/pages/OrdersPage.js
  src/main/js/patterns/Observable.js
  src/main/js/services/order.js
Labels: Avaliação A3, Avaliação A4.1

#77 Add restaurant data edition
  src/main/js/App.js
  src/main/js/components/AppBar.js
  src/main/js/pages/Login.js
  src/main/js/pages/RestaurantProfile.js
  src/main/js/pages/restaurantSignUp/RestaurantSignUp.js
Labels: Avaliação A3

#78 fix: update tests
  src/__snapshots__/RestaurantSignUpCEP.spec.js.snap
  src/__snapshots__/RestaurantSignUpCNPJ.spec.js.snap
  src/__snapshots__/RestaurantSignUpEmail.spec.js.snap
  src/__snapshots__/RestaurantSignUpSenha.spec.js.snap
  src/main/js/pages/restaurantSignUp/RestaurantSignUp.js
Labels: Avaliação A3
